using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using ResourceBooking.Core.Interfaces;

namespace ResourceBooking.Infrastructure.Storage;

public class LocalImageStorage : IImageStorage
{
    private readonly string root;

    public LocalImageStorage(IOptions<ImageStorageOptions> options, IHostEnvironment environment)
    {
        root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(options.Value.RootPath, environment.ContentRootPath));
        var webRoot = Path.GetFullPath(Path.Combine(environment.ContentRootPath, "wwwroot"));
        if (root.Equals(webRoot, StringComparison.OrdinalIgnoreCase) ||
            root.StartsWith(webRoot + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Image storage must be outside wwwroot.");
    }

    private string Resolve(string key)
    {
        // Keys are generated by the server, but validate again at the storage boundary.
        if (string.IsNullOrWhiteSpace(key) || Path.IsPathRooted(key) || key.Contains('\\') ||
            key.Split('/').Any(part => part is "" or "." or ".." || part.Contains(':')))
            throw new InvalidOperationException("Invalid image storage key.");
        var path = Path.GetFullPath(Path.Combine(root, key));
        if (!path.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Invalid image storage key.");
        return path;
    }

    public async Task SaveAsync(string key, Stream content, CancellationToken cancellationToken = default)
    {
        var path = Resolve(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        // CreateNew prevents accidental replacement of an existing asset.
        await using var target = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None,
            81920, FileOptions.Asynchronous);
        await content.CopyToAsync(target, cancellationToken);
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        try
        {
            return Task.FromResult<Stream?>(new FileStream(Resolve(key), FileMode.Open, FileAccess.Read,
                FileShare.Read | FileShare.Delete, 81920, FileOptions.Asynchronous));
        }
        catch (FileNotFoundException) { return Task.FromResult<Stream?>(null); }
        catch (DirectoryNotFoundException) { return Task.FromResult<Stream?>(null); }
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var path = Resolve(key);
        try { File.Delete(path); }
        catch (DirectoryNotFoundException) { }
        return Task.CompletedTask;
    }
}
